name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        
    - name: Checkoute code
      uses: actions/checkout@v4

    - name: Change permissions
      run: 'chmod 755 ./mvnw'

    - name: Build with Maven
      run: './mvnw clean package'

    - name: Show result after completed build
      run: 'ls -l ./target'
      
