name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'  # Adjust the Java version as needed

    - name: Change permissions
      run: 'chmod 755 ./mvnw'
      
    - name: Build with Maven
      run: |
        ./mvnw clean install
        # Add any other build commands or steps here

    - name: Run Unit Tests
      run: |
        ./mvnw test
        # Add any other test commands or steps here
